### PR TITLE
Update for Angular v14

### PR DESCRIPTION
**Pull request by devlinjunker**
Related: https://github.com/ui-router/angular/pull/967

Found these instructions for updating Angular versions in: https://github.com/ui-router/angular/blob/master/add_support_for_new_angular_version.txt so I am creating PR after running the following steps:
```
 - npx ng update @angular/core @angular/cli
 - git commit -m "chore: update to Angular 11"
 - yarn && yarn test
```

### CODE REVIEW

**Comment by devlinjunker** [comment]
@wawyed can we try to run the ci on these?

**Comment by wawyed** [comment]
Hmmm are you use you did this correctly? I don't see any package.json changes

**Comment by devlinjunker** [comment]
good point... I though followed the steps in that doc from the other repo, but I think you're right that something went wrong..

I have run `npx ng update @angular/core @angular/cli` and it looks better with more changes to commit:
```
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.2.2 to perform the update.
✔ Package successfully installed.
DEPRECATED: The 'defaultProject' workspace option has been deprecated. The project to use will be determined from the current working directory.
Using package manager: yarn
Collecting installed dependencies...
Found 27 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "14.2.2" (was "13.3.9")...
    Updating package.json with dependency @angular/animations @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/cli @ "14.2.2" (was "13.3.9")...
    Updating package.json with dependency @angular/compiler-cli @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency typescript @ "4.8.3" (was "4.4.4")...
    Updating package.json with dependency @angular/common @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/compiler @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/core @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/forms @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/platform-browser @ "14.2.1" (was "13.0.2")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "14.2.1" (was "13.0.2")...
UPDATE package.json (1793 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

❯ Remove 'defaultProject' option from workspace configuration.
  The project to use will be determined from the current working directory.
UPDATE angular.json (3360 bytes)
  Migration completed.

❯ Remove 'showCircularDependencies' option from browser and server builders.
  Migration completed.

❯ Replace 'defaultCollection' option in workspace configuration with 'schematicCollections'.
  Migration completed.

❯ Update Angular packages 'dependencies' and 'devDependencies' version prefix to '^' instead of '~'.
✔ Packages installed successfully.
  Migration completed.

❯ Remove 'package.json' files from library projects secondary entrypoints.
  Migration completed.

❯ Update TypeScript compilation target to 'ES2020'.
UPDATE src/tsconfig.json (502 bytes)
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ As of Angular version 13, `entryComponents` are no longer necessary.
UPDATE src/app/global/global.module.ts (516 bytes)
  Migration completed.

❯ In Angular version 14, the `pathMatch` property of `Routes` was updated to be a strict union of the two valid options: `'full'|'prefix'`.
  `Routes` and `Route` variables need an explicit type so TypeScript does not infer the property as the looser `string`.
  Migration completed.

❯ As of Angular version 14, Forms model classes accept a type parameter, and existing usages must be opted out to preserve backwards-compatibility.
  Migration completed.
```

**Comment by devlinjunker** [comment]
@wawyed can we:
1. merge https://github.com/ui-router/sample-app-angular/pull/772, then 
2. run the CI on this commit + verify it looks good to you
3. merge this PR
4. run CI on ui-router/angular PR: https://github.com/ui-router/angular/pull/967

**Pull request merged**
